target: priceFactor
baseline:
  derive_factor: false
  base_target: salePrice
  baseline_column: baselineMedian
  transactions_column: baselineTransactions
correlation_threshold: 0.9
drop_columns: []
force_keep:
  - street
  - suburb
  - propertyType
  - bed
  - bath
  - car
  - comparableCount
  - saleYear
  - saleMonth
