target: salePrice
log_target: true

input: 
  path: data/training
  X: X.parquet
  y: y.parquet
  feature_scores: feature_scores.csv

model_path:
  base: ./models
  timestamped: true

split:
  test_size: 0.2
  random_state: 42

manual_feature_adjustments:
  include: []     # e.g., ["medianPrice_suburb_3m"]
  exclude: []     # e.g., ["street"]   # if you decide to drop it

models:
  LinearRegression:
    enabled: true
    grid: {}

  Ridge:
    enabled: true
    grid:
      alpha: [0.01, 0.1, 1.0, 10.0]   # regularisation strength

  ElasticNet:
    enabled: true
    grid:
      alpha: [0.01, 0.1, 1.0]      # regularisation strength
      l1_ratio: [0.1, 0.5, 0.9]    # 0 = Ridge, 1 = Lasso

  Lasso:
    enabled: true
    grid:
      alpha: [0.001, 0.01, 0.1, 1.0]  # regularisation strength
      
  RandomForestRegressor:
    enabled: true
    grid:
      n_estimators: [300, 600]
      max_depth: [null, 20, 30]
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2, 4]
      max_features: ['sqrt', 0.5]
  GradientBoostingRegressor:
    enabled: true
    grid:
      n_estimators: [200, 400]
      learning_rate: [0.05, 0.1]
      max_depth: [2, 3, 4]
      subsample: [0.7, 0.85, 1.0]
      min_samples_leaf: [1, 3]
