split:
  test_size: 0.2
  random_state: 42
models:
  LinearRegression:
    enabled: true
    grid: {}
  RandomForestRegressor:
    enabled: true
    grid:
      model__alpha: &id001
      - 0.1
      - 1.0
      - 10.0
      model__l1_ratio: &id002
      - 0.1
      - 0.5
      - 0.9
  GradientBoostingRegressor:
    enabled: true
    grid:
      model__alpha: *id001
      model__l1_ratio: *id002
  Lasso:
    enabled: true
    grid:
      model__alpha: *id001
      model__l1_ratio: *id002
  ElasticNet:
    enabled: true
    grid:
      model__alpha: *id001
      model__l1_ratio: *id002
