model_path:
  base: models

models:
  LinearRegression:
    enabled: true
    grid: {}
  Ridge:
    enabled: true
    grid:
      alpha: [0.01, 0.1, 1.0, 10.0]
  ElasticNet:
    enabled: true
    grid:
      alpha: [0.01, 0.1, 1.0]
      l1_ratio: [0.1, 0.5, 0.9]
  Lasso:
    enabled: true
    grid:
      alpha: [0.001, 0.01, 0.1, 1.0]
  RandomForestRegressor:
    enabled: true
    grid:
      n_estimators: [300, 600]
      max_depth: [null, 20, 30]
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2, 4]
      max_features: ["sqrt", 0.5]
  GradientBoostingRegressor:
    enabled: true
    grid:
      n_estimators: [200, 400]
      learning_rate: [0.05, 0.1]
      max_depth: [2, 3, 4]
      subsample: [0.7, 0.85, 1.0]
      min_samples_leaf: [1, 3]

targets:
  - name: price_future_6m
    target: price_future_6m_delta
    input:
      path: data/training/price_future_6m_delta
      X: X.parquet
      y: y.parquet
      feature_scores: feature_scores.parquet
    split:
      month_column: saleYearMonth
      validation_month: 2023-03
    log_target: false
  - name: price_future_12m
    target: price_future_12m_smooth_delta
    input:
      path: data/training/price_future_12m_smooth_delta
      X: X.parquet
      y: y.parquet
      feature_scores: feature_scores.parquet
    split:
      month_column: saleYearMonth
      validation_month: 2023-03
    log_target: false
