target: salePrice
log_target: true

input:
  path: data/training
  X: X.csv
  y: y.csv
  feature_scores: feature_scores.parquet

model_path:
  base: models

split:
  month_column: saleYearMonth
  validation_month: null  # optional; defaults to latest month present in X

models:
  LinearRegression:
    enabled: true
    grid: {}

  Ridge:
    enabled: true
    grid:
      alpha: [0.01, 0.1, 1.0, 10.0]

  ElasticNet:
    enabled: true
    grid:
      alpha: [0.01, 0.1, 1.0]
      l1_ratio: [0.1, 0.5, 0.9]

  Lasso:
    enabled: true
    grid:
      alpha: [0.001, 0.01, 0.1, 1.0]

  RandomForestRegressor:
    enabled: true
    grid:
      n_estimators: [300, 600]
      max_depth: [null, 20, 30]
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2, 4]
      max_features: ["sqrt", 0.5]

  GradientBoostingRegressor:
    enabled: true
    grid:
      n_estimators: [200, 400]
      learning_rate: [0.05, 0.1]
      max_depth: [2, 3, 4]
      subsample: [0.7, 0.85, 1.0]
      min_samples_leaf: [1, 3]
