data_source:
  path: data/raw
  pattern: "*.csv"
  encoding: "utf-8-sig"

min_non_null_fraction: 0.35
special_to_ascii:
  "²": "2"
normalise_text_columns: [streetAddress, propertyType]

numeric_candidates:
  - bed
  - bath
  - car
  - landSizeM2
  - floorSizeM2
  - yearBuilt
  - salePrice
  - postcode

bucketing_rules:
  agency: 20
  landUse: 15
  propertyType: 15

required_columns:
  - salePrice
  - bed
  - bath


category_mappings:
  propertyType:
    House: [house, townhouse, dwelling]
    Unit: [unit, villa, duplex]
    Apartment: [flat, studio]
  agencyBrand:
    source: agency
    default: Other
    mode: contains   # substring match after normalisation
    rules:
      Noel Jones:     [NOEL JONES]
      Barry Plant:    [BARRY PLANT]
      Jellis Craig:   [JELLIS CRAIG]
      Ray White:      [RAY WHITE]
      Harcourts:      [HARCOURTS]
      Woodards:       [WOODARDS]
      Biggin & Scott: [BIGGIN & SCOTT]
      Fletchers:      [FLETCHERS]
      Unknown:        [UNKNOWN]
      Other:          [OTHER]
  developmentZone:
    # Residential Growth Zone (Schedules 1–3)
    RGZ1: [residential growth zone - schedule 1, residential growth zone schedule 1, rgz1]
    RGZ2: [residential growth zone - schedule 2, residential growth zone schedule 2, rgz2]
    RGZ3: [residential growth zone - schedule 3, residential growth zone schedule 3, rgz3]
    # Neighbourhood Residential Zone (Schedules 1–4)
    NRZ1: [neighbourhood residential zone - schedule 1, neighbourhood residential zone schedule 1, nrz1]
    NRZ2: [neighbourhood residential zone - schedule 2, neighbourhood residential zone schedule 2, nrz2]
    NRZ3: [neighbourhood residential zone - schedule 3, neighbourhood residential zone schedule 3, nrz3]
    NRZ4: [neighbourhood residential zone - schedule 4, neighbourhood residential zone schedule 4, nrz4]
    # General Residential Zone (Schedules 1–3)
    GRZ1: [general residential zone - schedule 1, general residential zone schedule 1, grz1]
    GRZ2: [general residential zone - schedule 2, general residential zone schedule 2, grz2]
    GRZ3: [general residential zone - schedule 3, general residential zone schedule 3, grz3]
    # Other common zones
    C1Z: [commercial 1 zone, c1z]
    C2Z: [commercial 2 zone, c2z]
    MUZ: [mixed use zone, muz]
    IN1Z: [industrial 1 zone, in1z]
    IN2Z: [industrial 2 zone, in2z]
    IN3Z: [industrial 3 zone, in3z]
    LDRZ: [low density residential zone, ldrz]
    TZ:  [township zone, tz]
    UGZ1: [urban growth zone - schedule 1, urban growth zone schedule 1, ugz1]
    UGZ2: [urban growth zone - schedule 2, urban growth zone schedule 2, ugz2]
    UGZ3: [urban growth zone - schedule 3, urban growth zone schedule 3, ugz3]