data_source:
  path: data
  pattern: "*.csv"
  # Set filter_columns to false to include all columns from the data files
  filter_columns: false
  # If filter_columns is true, only these columns will be included in the output
  include_columns:
    - streetAddress
    - suburb
    - saleDate
    - salePrice
    - bed
    - bath
    - car
    - propertyType
    - postcode
cleaning:
  required_columns:
    - salePrice
    - bed
    - bath
  primary_target: salePrice
  min_comparable_count: 2
  comparable_columns:
    - street
    - propertyType
    - bed
    - bath
    - car
  numeric_candidates:
    - bed
    - bath
    - car
    - landSizeM2
    - floorSizeM2
    - yearBuilt
    - salePrice
    - postcode
  bucketing_rules:
    agency: 20
    landUse: 15
    propertyType: 15
  category_mappings:
    propertyType:
      House:
        - house
        - townhouse
        - dwelling
      Unit:
        - unit
        - villa
        - duplex
      Apartment:
        - flat
        - studio
derivations:
  street:
    enabled: true
    source: streetAddress
    output: street
    drop_unknown: true
    config:
      unknown_value: Unknown
  propertyType:
    enabled: true
    config:
      unit_keywords:
        - unit
        - flat
        - apartment
        - villa
        - studio
        - duplex
      house_keywords:
        - house
        - detached
        - dwelling
        - residence
        - townhouse
      unit_label: Unit
      house_label: House
      unknown_value: ""
  street_year_median_price:
    enabled: true
    group_by:
      - street
      - saleYear
    target: salePrice
    aggregate: median
    output: streetYearMedianPrice
  postcode_prefix:
    enabled: true
    source: postcode
    length: 1
    output: postcodePrefix
  price_factor:
    enabled: true
    numerator: salePrice
    denominator: streetYearMedianPrice
    output: priceFactor
    min_value: 0.01
