data_source:
  path: data
  pattern: "*.csv"
  # Set filter_columns to false to include all columns from the data files
  filter_columns: false
  # If filter_columns is true, only these columns will be included in the output
  include_columns:
    - streetAddress
    - suburb
    - saleDate
    - salePrice
    - bed
    - bath
    - car
    - propertyType
    - postcode
cleaning:
  required_columns:
    - salePrice
    - bed
    - bath
  primary_target: salePrice
  min_comparable_count: 2
  # Early standardisation of raw tokens before consolidation
  # Use this to normalise noisy inputs (AU terminology),
  # then rely on category_mappings.propertyType for final grouping.
  standardise:
    propertyType:
      apartment:
        - apt
        - apts
      townhouse:
        - town house
        - town-house
      unit:
        - units
        - unit/apartment
      house:
        - residence
        - detached dwelling
  comparable_columns:
    - street
    - propertyType
    - bed
    - bath
    - car
  numeric_candidates:
    - bed
    - bath
    - car
    - landSizeM2
    - floorSizeM2
    - yearBuilt
    - salePrice
    - postcode
  bucketing_rules:
    agency: 20
    landUse: 15
    propertyType: 15
  category_mappings:
    propertyType:
      House:
        - house
        - townhouse
        - dwelling
      Unit:
        - unit
        - villa
        - duplex
      Apartment:
        - flat
        - studio
    developmentZone:
      # Residential Growth Zone (Schedules 1–3)
      RGZ1:
        - residential growth zone - schedule 1
        - residential growth zone schedule 1
        - rgz1
      RGZ2:
        - residential growth zone - schedule 2
        - residential growth zone schedule 2
        - rgz2
      RGZ3:
        - residential growth zone - schedule 3
        - residential growth zone schedule 3
        - rgz3
      # Neighbourhood Residential Zone (Schedules 1–4)
      NRZ1:
        - neighbourhood residential zone - schedule 1
        - neighbourhood residential zone schedule 1
        - nrz1
      NRZ2:
        - neighbourhood residential zone - schedule 2
        - neighbourhood residential zone schedule 2
        - nrz2
      NRZ3:
        - neighbourhood residential zone - schedule 3
        - neighbourhood residential zone schedule 3
        - nrz3
      NRZ4:
        - neighbourhood residential zone - schedule 4
        - neighbourhood residential zone schedule 4
        - nrz4
      # General Residential Zone (Schedules 1–3)
      GRZ1:
        - general residential zone - schedule 1
        - general residential zone schedule 1
        - grz1
      GRZ2:
        - general residential zone - schedule 2
        - general residential zone schedule 2
        - grz2
      GRZ3:
        - general residential zone - schedule 3
        - general residential zone schedule 3
        - grz3
      # Other common zones
      C1Z:
        - commercial 1 zone
        - c1z
      C2Z:
        - commercial 2 zone
        - c2z
      MUZ:
        - mixed use zone
        - muz
      IN1Z:
        - industrial 1 zone
        - in1z
      IN2Z:
        - industrial 2 zone
        - in2z
      IN3Z:
        - industrial 3 zone
        - in3z
      LDRZ:
        - low density residential zone
        - ldrz
      TZ:
        - township zone
        - tz
      UGZ1:
        - urban growth zone - schedule 1
        - urban growth zone schedule 1
        - ugz1
      UGZ2:
        - urban growth zone - schedule 2
        - urban growth zone schedule 2
        - ugz2
      UGZ3:
        - urban growth zone - schedule 3
        - urban growth zone schedule 3
        - ugz3
derivations:
  street:
    enabled: true
    source: streetAddress
    output: street
    drop_unknown: true
    config:
      unknown_value: Unknown
  street_year_median_price:
    enabled: true
    group_by:
      - street
      - saleYear
    target: salePrice
    aggregate: median
    output: streetYearMedianPrice
  postcode_prefix:
    enabled: true
    source: postcode
    length: 2
    output: postcodePrefix
  price_factor:
    enabled: true
    numerator: salePrice
    denominator: streetYearMedianPrice
    output: priceFactor
    min_value: 0.01